refactor(components): typings
NSFI/ppfish-components pull request #37
Opened 2020-12-16 02:29 UTC by bushuai

1. 增加组件类型标注；
	- `react-components` 组件不对外暴露 API，所以各组件 **src** 内下的部分未进行标注
2. 由于使用了 **Omit** 等特性，将 **typescript** 升级至 `v4.1.3`;
3. 将 ESLint `parser`切换 为 **@typescript-eslint/parser**。

2020-12-21 07:06 UTC, hangaoke1 approved these changes

2020-12-24 02:19 UTC, hangaoke1 commented on source/components/Drawer/Drawer.tsx
> +        // wrapperClassName={wrapperClassName}
这个为何注释掉，RcDrawer中是有使用到的

2020-12-24 02:32 UTC, bushuai commented on source/components/Drawer/Drawer.tsx
> +        // wrapperClassName={wrapperClassName}
核对了一下，这里处理有误，后续提交修正。

2020-12-24 03:14 UTC, hepeguo approved these changes

2020-12-24 03:17 UTC, hepeguo approved these changes

2020-12-24 05:25 UTC, hepeguo commented on source/components/DatePicker/TimeSelect.tsx
> +        {...this.props}
这里怎么没有和source/components/DatePicker/TimePicker.tsx 第82保持一致

2020-12-24 05:28 UTC, bushuai commented on source/components/DatePicker/TimeSelect.tsx
> +        {...this.props}
我核对一下，DatePicker 代码比较多，可能有遗漏的地方。

2020-12-24 05:57 UTC, bushuai commented on source/components/Animate/animate.tsx
> +import AnimateChild from './child'
👌  嗯嗯，好的。

2020-12-24 06:42 UTC, gtopia approved these changes

2020-12-24 06:55 UTC, gtopia requested changes

2020-12-24 06:55 UTC, gtopia commented on source/components/PicturePreview/index.tsx
> +                  // active={true}
这里的active不能直接注释掉，会影响当前图片的展示。可以把这里的active标识放到class里：
`                <img
                  key={'pic_' + index}
                  className="img active"
                  src={item.src ? item.src : null}
                  alt={item.name ? item.name : null}
                  ref={node => (this.imgEl = node)}
                />`，然后在对应的样式文件里做修改：
把「.img[active]」改为「.img.active」，改完后需要跑一下测试用例，在官网上看一下demo是否正常。

2020-12-24 06:55 UTC, gtopia commented on source/components/PicturePreview/__tests__/__snapshots__/demo.test.js.snap
> -            active="true"
这里的active属性不能直接去掉，需要改一下代码，重新运行测试用例。

2020-12-24 06:58 UTC, bushuai commented on source/components/PicturePreview/index.tsx
> +                  // active={true}
👍  嗯嗯，我修改后再测试下。

2020-12-24 07:11 UTC, bushuai commented on source/components/DatePicker/TimeSelect.tsx
> +        {...this.props}
核对了一下代码，这里直接传 **this.props** 就可以。

补充子组件的 **props** 定义后没有同步移除此处 **pick** 操作...

2020-12-24 07:40 UTC, bushuai commented on source/components/PicturePreview/__tests__/__snapshots__/demo.test.js.snap
> -            active="true"
已重新生成 snapshot 并执行通过该用例。

2020-12-24 08:16 UTC, gtopia approved these changes

2020-12-25 02:00 UTC, merged